site_name: Kiae - The Better CloudNative AppDevPlatform base on the Kubernetes and Istio
repo_url: https://github.com/kiaedev/kiae
docs_dir: docs
site_description: >-
  The Better CloudNative AppDevPlatform

nav:
  - Overview: index.md
  - Concepts: concepts.md
  - Architecture: architecture.md
  - Getting Started: getting-started.md
  - Operator Manual:
      - Installation: operator-manual/installation.md
      - Git Provider: operator-manual/git-provider.md
      - Image Registry: operator-manual/image-registry.md
      - Image Builder: operator-manual/image-builder.md
  - User Guide:
      - Project: user-guide/project.md
      - Image: user-guide/image.md
      - Application: user-guide/application.md
  - FAQ: FAQ.md
  - Roadmap: roadmap.md
  - Releases ⧉: https://github.com/kiaedev/kiae/releases
  - Milestones ⧉: https://github.com/kiaedev/kiae/milestones

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.indexes
  font:
    text: Work Sans
  palette:
    - primary: blue grey
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - i18n:
      default_language: en
      default_language_only: false
      docs_structure: folder
      languages:
        en:
          name: English
          build: true
          site_name: "The Better CloudNative AppDevPlatform"
        zh:
          name: 中文
          build: true
          site_name: "更好的云原生应用引擎"
      nav_translations:
        zh:
          Overview: 概述
          Concepts: 概念
          Architecture: 架构
          Getting Started: 快速开始
          Installation: 安装
          Operator Manual: 运维手册
          User Guide: 用户教程
          Git Provider: Git提供商
          Image Registry: 镜像仓库
          Image Builder: 镜像构建器
          Project: 项目管理
          Image: 镜像管理
          Application: 应用管理
          FAQ: 常见问题
          Roadmap: 路线图
          Releases ⧉: 发布历史
          Milestones ⧉: 里程碑
